name: instaclone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.2.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.3.2
  platform_device_id_v3: ^1.0.0
  flutter_local_notifications: ^17.0.1
  #image_package
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.1.1
  # Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
